#!/bin/bash
echo "Content-type: text/plain"
echo ""

if [ $QUERY_STRING != "" ]
    then
        TIMER_END=${QUERY_STRING/"endMinutes="/}
        echo $TIMER_END > /tmp/timerEndMinutes
fi

cat /tmp/timerEndMinutes

